Mock tests (initial approach)
glenn-m/promR pull request #32
Opened 2019-05-05 14:38 UTC by konradzdeb

Hi,

This doesn't fully close #10 but I wanted to show you the approach before replacing the rest of tests. The idea is a follows:

1. As per [previoulsy linked chat](https://stackoverflow.com/a/41777777/1655567) I've committed RDS object containing instant response from `httr::GET`
2. `Stub` for `httr::GET` is created via `mockery` package

This initial test on a returned object being data frame passes. I reckon that this could be further developed.

2019-05-05 15:15 UTC, glenn-m requested changes
It looks good apart from the Vignette which looks unfinished, might be worthwhile submitting it under a different PR once it's done?

2019-05-05 15:15 UTC, glenn-m commented on vignettes/basic-usage.Rmd
> +The `promR` package offers `Promethous` class that provides two methods of sourcing data:
Typo here, `Promethous`

2019-05-05 15:15 UTC, glenn-m commented on tests/testthat/test-response-check.R
> +test_that(desc = "Check that class functions source data.",
The approach looks good, removes the need to call out to a service which may go down. I reckon we can roll out this pattern to the other main API calls.

2019-05-05 17:40 UTC, konradzdeb commented
Sorry, I’ve mistakenly committed this vignette to wrong branch!

--
Konrad

> On 5 May 2019, at 16:15, Glenn McDonald <notifications@github.com> wrote:
> 
> @glenn-m requested changes on this pull request.
> 
> It looks good apart from the Vignette which looks unfinished, might be worthwhile submitting it under a different PR once it's done?
> 
> In vignettes/basic-usage.Rmd:
> 
> > +  %\VignetteEngine{knitr::rmarkdown}
> +  %\VignetteEncoding{UTF-8}
> +---
> +
> +```{r setup, include = FALSE}
> +knitr::opts_chunk$set(
> +  collapse = TRUE,
> +  comment = "#>"
> +)
> +```
> +
> +Prometheus is an open-source software project recording real-time metrics using HTTP pull model [^1]. Prometheus records metrics in a time series database and allows for high-dimensionality. 
> +
> +## Queries
> +
> +The `promR` package offers `Promethous` class that provides two methods of sourcing data:
> Typo here, Promethous
> 
> In tests/testthat/test-response-check.R:
> 
> > @@ -72,8 +72,22 @@ test_that(desc = "OK when application type is json and status code is 200.",
>  
>  # Test whether package can pull some sample data
>  # Source query data once to use later across tests
> -prom <-
> -  Prometheus$new(host = "http://demo.robustperception.io", port = 9090)
> +
> +# Create an object
> +prom <- Prometheus$new(host = "http://demo.robustperception.io",
> +                       port = 9090)
> +
> +test_that(desc = "Check that class functions source data.",
> The approach looks good, removes the need to call out to a service which may go down. I reckon we can roll out this pattern to the other main API calls.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-05 19:07 UTC, konradzdeb commented on vignettes/basic-usage.Rmd
> +The `promR` package offers `Promethous` class that provides two methods of sourcing data:
:)

2019-05-07 06:49 UTC, glenn-m approved these changes

2019-05-07 07:00 UTC, merged